# Versão 2 do Docker-Compose
version: '2'

services:
    
    nginx:
        restart: "always"
        image: jchengdeveng/k8s-rancher-nginx:latest
        ports:
            - "80:80"
        # links:
        #     # Colocar mais nós para escalar
        #     - node
        #     # - node-2
        networks: 
          - k8s-rancher    
    redis:
        restart: "always"
        image: jchengdeveng/k8s-rancher-redis:latest
        ports:
            - 6379
        networks:
          - k8s-rancher
    mysql:
        restart: "always"
        image: mysql
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: books
            MYSQL_USER: apitreinamento
            MYSQL_PASSWORD: 123 
        networks: 
          - k8s-rancher
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    node:
        restart: "always"
        image: jchengdeveng/k8s-rancher-node:latest
        # links:
        #     - redis
        #     - mysql
        networks: 
          - k8s-rancher
        ports:
            - 8080
        volumes:
            -  volumeteste:/tmp/volumeteste
    
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Mapeamento dos volumes
volumes:
    volumeteste:
        external: false
networks: 
  k8s-rancher:
    name: k8s-rancher

